# Twitter Credentials
twitter_account_id = 'YOUR_TWITTER_ACCOUNT_ID'
API_KEY = 'YOUR_TWITTER_API_KEY'
API_SECRET_KEY = 'YOUR_TWITTER_API_SECRET_KEY'
ACCESS_KEY = 'YOUR_TWITTER_ACCESS_KEY'
ACCESS_SECRET_KEY = 'YOUR_TWITTER_ACCESS_SECRET_KEY'

# Telegram Credentials
apiToken = 'YOUR_TELEGRAM_API_TOKEN'
chatID = 'YOUR_TELEGRAM_CHAT_ID'

